version: '3.8'
services:
  hire_api:
    container_name: hire_api
    restart: always
    build: .
    ports:
     - ${PORT}:${PORT}
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_DB=$DATABASE_DB
      - DATABASE_URL=$DATABASE_URL
      - ALLOWED_HOSTS=$ALLOWED_HOSTS


