version: '3.8'
services:
  hire_api:
    container_name: hire_api
    restart: always
    build: .
    ports:
     - ${PORT}:${PORT}
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - DATABASE_URL=$DATABASE_URL
      - ALLOWED_HOSTS=$ALLOWED_HOSTS


